service: lametric-displify
provider:
  name: aws
  runtime: java8
  region: eu-central-1
  memorySize: 512
  timeout: 10
  versionFunctions: false

package:
  artifact: target/lametric-displify-1.0.0-SNAPSHOT.jar

functions:
  displify:
    handler: de.ketrwu.lametric.api.DisplifyHandler
    events:
    - http:
        path: /displify
        method: GET